apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  labels:
    app: myappdeployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myappdeployment
  template:
    metadata:
      labels:
        app: myapp
      spec:
        imagePullSecrets: 
        -  name: dockercreds  
      containers:
       - name: myapp
         image: changan1111/newdocker:latest
         ports:
            - containerPort: 3000